apiVersion: v1
kind: Service
metadata:
  name: backend-country
  labels:
    service: backend-country
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: backend-country
